from asyncua import ua

from dataclasses import dataclass, field

from core.registry.datatyperegistry import DataTypeRegistry

from datatypes.custom.numbers import DINT, INT, SINT, REAL
from datatypes.custom.bool import BOOL

@DataTypeRegistry.register
@dataclass
class CHANNEL_HSC_I_0:
    Fault: BOOL = field(init=False, default_factory=BOOL)
    Uncertain: BOOL = field(init=False, default_factory=BOOL)
    RolloverLeqRollunder: BOOL = field(init=False, default_factory=BOOL)
    NotANumber: BOOL = field(init=False, default_factory=BOOL)
    MissingPulseAlarm: BOOL = field(init=False, default_factory=BOOL)
    ZeroFrequencyAlarm: BOOL = field(init=False, default_factory=BOOL)
    ZeroFrequencyAvgAlarm: BOOL = field(init=False, default_factory=BOOL)
    FrequencyAlarm: BOOL = field(init=False, default_factory=BOOL)
    FrequencyAvgAlarm: BOOL = field(init=False, default_factory=BOOL)
    PulseWidthAlarm: BOOL = field(init=False, default_factory=BOOL)
    PulseWidthAvgAlarm: BOOL = field(init=False, default_factory=BOOL)
    AccelAlarm: BOOL = field(init=False, default_factory=BOOL)
    AccelAvgAlarm: BOOL = field(init=False, default_factory=BOOL)
    DecelAlarm: BOOL = field(init=False, default_factory=BOOL)
    DecelAvgAlarm: BOOL = field(init=False, default_factory=BOOL)
    FrequencyOverrange: BOOL = field(init=False, default_factory=BOOL)
    PartialAvgFrequency: BOOL = field(init=False, default_factory=BOOL)
    PartialAvgPulseWidth: BOOL = field(init=False, default_factory=BOOL)
    Direction: BOOL = field(init=False, default_factory=BOOL)
    StoredDirection: BOOL = field(init=False, default_factory=BOOL)
    Rollover: BOOL = field(init=False, default_factory=BOOL)
    Rollunder: BOOL = field(init=False, default_factory=BOOL)
    DataA: BOOL = field(init=False, default_factory=BOOL)
    DataB: BOOL = field(init=False, default_factory=BOOL)
    DataZ: BOOL = field(init=False, default_factory=BOOL)
    DataAOverridden: BOOL = field(init=False, default_factory=BOOL)
    DataBOverridden: BOOL = field(init=False, default_factory=BOOL)
    DataZOverridden: BOOL = field(init=False, default_factory=BOOL)
    Count: DINT = field(init=False, default_factory=DINT)
    StoredCount: DINT = field(init=False, default_factory=DINT)
    ScaledCount: REAL = field(init=False, default_factory=REAL)
    ScaledStoredCount: REAL = field(init=False, default_factory=REAL)
    RevolutionCount: INT = field(init=False, default_factory=INT)
    StoredRevolutionCount: INT = field(init=False, default_factory=INT)
    Frequency: REAL = field(init=False, default_factory=REAL)
    FrequencyAvg: REAL = field(init=False, default_factory=REAL)
    StoredFrequency: REAL = field(init=False, default_factory=REAL)
    ScaledFrequency: REAL = field(init=False, default_factory=REAL)
    ScaledFrequencyAvg: REAL = field(init=False, default_factory=REAL)
    ScaledStoredFrequency: REAL = field(init=False, default_factory=REAL)
    PulseWidth: REAL = field(init=False, default_factory=REAL)
    PulseWidthAvg: REAL = field(init=False, default_factory=REAL)
    StoredPulseWidth: REAL = field(init=False, default_factory=REAL)
    QuadratureErrorCount: SINT = field(init=False, default_factory=SINT)
    CountChangeIndicator: SINT = field(init=False, default_factory=SINT)
    Accel: REAL = field(init=False, default_factory=REAL)
    AccelAvg: REAL = field(init=False, default_factory=REAL)
    StoredAccel: REAL = field(init=False, default_factory=REAL)
    ScaledAccel: REAL = field(init=False, default_factory=REAL)
    ScaledAccelAvg: REAL = field(init=False, default_factory=REAL)
    ScaledStoredAccel: REAL = field(init=False, default_factory=REAL)

@DataTypeRegistry.register
@dataclass
class CHANNEL_HSC_O_0:
    Reset: BOOL = field(init=False, default_factory=BOOL)
    Hold: BOOL = field(init=False, default_factory=BOOL)
    Load: BOOL = field(init=False, default_factory=BOOL)
    Store: BOOL = field(init=False, default_factory=BOOL)
    Direction: BOOL = field(init=False, default_factory=BOOL)
    RolloverAck: BOOL = field(init=False, default_factory=BOOL)
    RollunderAck: BOOL = field(init=False, default_factory=BOOL)
    FrequencyAlarmUnlatch: BOOL = field(init=False, default_factory=BOOL)
    FrequencyAvgAlarmUnlatch: BOOL = field(init=False, default_factory=BOOL)
    PulseWidthAlarmUnlatch: BOOL = field(init=False, default_factory=BOOL)
    PulseWidthAvgAlarmUnlatch: BOOL = field(init=False, default_factory=BOOL)
    ZeroFrequencyAlarmUnlatch: BOOL = field(init=False, default_factory=BOOL)
    ZeroFrequencyAvgAlarmUnlatch: BOOL = field(init=False, default_factory=BOOL)
    MissingPulseAlarmEn: BOOL = field(init=False, default_factory=BOOL)
    MissingPulseAlarmUnlatch: BOOL = field(init=False, default_factory=BOOL)
    AccelAlarmUnlatch: BOOL = field(init=False, default_factory=BOOL)
    DecelAlarmUnlatch: BOOL = field(init=False, default_factory=BOOL)
    AccelAvgAlarmUnlatch: BOOL = field(init=False, default_factory=BOOL)
    DecelAvgAlarmUnlatch: BOOL = field(init=False, default_factory=BOOL)
    ResetFrequencyOverrange: BOOL = field(init=False, default_factory=BOOL)
    ResetQuadratureErrorCount: BOOL = field(init=False, default_factory=BOOL)
    RolloverValue: DINT = field(init=False, default_factory=DINT)
    RollunderValue: DINT = field(init=False, default_factory=DINT)
    ZeroFrequencyAlarmLimit: REAL = field(init=False, default_factory=REAL)
    LoadCountValue: DINT = field(init=False, default_factory=DINT)
    LoadRevolutionValue: INT = field(init=False, default_factory=INT)
    OverrideDataAEn: BOOL = field(init=False, default_factory=BOOL)
    OverrideDataBEn: BOOL = field(init=False, default_factory=BOOL)
    OverrideDataZEn: BOOL = field(init=False, default_factory=BOOL)
    OverrideDataAValue: BOOL = field(init=False, default_factory=BOOL)
    OverrideDataBValue: BOOL = field(init=False, default_factory=BOOL)
    OverrideDataZValue: BOOL = field(init=False, default_factory=BOOL)
    MissingPulseAlarmLimit: DINT = field(init=False, default_factory=DINT)
