from dataclasses import dataclass, field

from asyncua import ua

from core.registry.datatyperegistry import DataTypeRegistry

from datatypes.custom.numbers import DINT, REAL, LINT
from datatypes.custom.bool import BOOL

@DataTypeRegistry.register
@dataclass
class ALARM:
    EnableIn: BOOL = field(init=False, default_factory=BOOL)
    In: REAL = field(init=False, default_factory=REAL)
    HHLimit: REAL = field(init=False, default_factory=REAL)
    HLimit: REAL = field(init=False, default_factory=REAL)
    LLimit: REAL = field(init=False, default_factory=REAL)
    LLLimit: REAL = field(init=False, default_factory=REAL)
    Deadband: REAL = field(init=False, default_factory=REAL)
    ROCPosLimit: REAL = field(init=False, default_factory=REAL)
    ROCPeriod: REAL = field(init=False, default_factory=REAL)
    EnableOut: BOOL = field(init=False, default_factory=BOOL)
    HHAlarm: BOOL = field(init=False, default_factory=BOOL)
    HAlarm: BOOL = field(init=False, default_factory=BOOL)
    LAlarm: BOOL = field(init=False, default_factory=BOOL)
    LLAlarm: BOOL = field(init=False, default_factory=BOOL)
    ROCPosAlarm: BOOL = field(init=False, default_factory=BOOL)
    ROCNegAlarm: BOOL = field(init=False, default_factory=BOOL)
    ROC: REAL = field(init=False, default_factory=REAL)
    Status: DINT = field(init=False, default_factory=DINT)
    InstructFault: BOOL = field(init=False, default_factory=BOOL)
    DeadbandInv: BOOL = field(init=False, default_factory=BOOL)
    ROCPosLimitInv: BOOL = field(init=False, default_factory=BOOL)
    ROCNegLimitInv: BOOL = field(init=False, default_factory=BOOL)
    ROCPeriodInv: BOOL = field(init=False, default_factory=BOOL)
    
@DataTypeRegistry.register
@dataclass
class ALARM_ANALOG:
    EnableIn: BOOL = field(init=False, default_factory=BOOL)
    In: REAL = field(init=False, default_factory=REAL)
    InFault: BOOL = field(init=False, default_factory=BOOL)
    HHEnabled: BOOL = field(init=False, default_factory=BOOL)
    HEnabled: BOOL = field(init=False, default_factory=BOOL)
    LEnabled: BOOL = field(init=False, default_factory=BOOL)
    LLEnabled: BOOL = field(init=False, default_factory=BOOL)
    AckRequired: BOOL = field(init=False, default_factory=BOOL)
    ProgAckAll: BOOL = field(init=False, default_factory=BOOL)
    OperAckAll: BOOL = field(init=False, default_factory=BOOL)
    HHProgAck: BOOL = field(init=False, default_factory=BOOL)
    HHOperAck: BOOL = field(init=False, default_factory=BOOL)
    HProgAck: BOOL = field(init=False, default_factory=BOOL)
    HOperAck: BOOL = field(init=False, default_factory=BOOL)
    LProgAck: BOOL = field(init=False, default_factory=BOOL)
    LOperAck: BOOL = field(init=False, default_factory=BOOL)
    LLProgAck: BOOL = field(init=False, default_factory=BOOL)
    LLOperAck: BOOL = field(init=False, default_factory=BOOL)
    ROCPosProgAck: BOOL = field(init=False, default_factory=BOOL)
    ROCPosOperAck: BOOL = field(init=False, default_factory=BOOL)
    ROCNegProgAck: BOOL = field(init=False, default_factory=BOOL)
    ROCNegOperAck: BOOL = field(init=False, default_factory=BOOL)
    ProgSuppress: BOOL = field(init=False, default_factory=BOOL)
    OperSuppress: BOOL = field(init=False, default_factory=BOOL)
    ProgUnsuppress: BOOL = field(init=False, default_factory=BOOL)
    OperUnsuppress: BOOL = field(init=False, default_factory=BOOL)
    HHOperShelve: BOOL = field(init=False, default_factory=BOOL)
    HOperShelve: BOOL = field(init=False, default_factory=BOOL)
    LOperShelve: BOOL = field(init=False, default_factory=BOOL)
    LLOperShelve: BOOL = field(init=False, default_factory=BOOL)
    ROCPosOperShelve: BOOL = field(init=False, default_factory=BOOL)
    ROCNegOperShelve: BOOL = field(init=False, default_factory=BOOL)
    ProgUnshelveAll: BOOL = field(init=False, default_factory=BOOL)
    HHOperUnshelve: BOOL = field(init=False, default_factory=BOOL)
    HOperUnshelve: BOOL = field(init=False, default_factory=BOOL)
    LOperUnshelve: BOOL = field(init=False, default_factory=BOOL)
    LLOperUnshelve: BOOL = field(init=False, default_factory=BOOL)
    ROCPosOperUnshelve: BOOL = field(init=False, default_factory=BOOL)
    ROCNegOperUnshelve: BOOL = field(init=False, default_factory=BOOL)
    ProgDisable: BOOL = field(init=False, default_factory=BOOL)
    OperDisable: BOOL = field(init=False, default_factory=BOOL)
    ProgEnable: BOOL = field(init=False, default_factory=BOOL)
    OperEnable: BOOL = field(init=False, default_factory=BOOL)
    AlarmCountReset: BOOL = field(init=False, default_factory=BOOL)
    HHMinDurationEnable: BOOL = field(init=False, default_factory=BOOL)
    HMinDurationEnable: BOOL = field(init=False, default_factory=BOOL)
    LMinDurationEnable: BOOL = field(init=False, default_factory=BOOL)
    LLMinDurationEnable: BOOL = field(init=False, default_factory=BOOL)
    HHLimit: REAL = field(init=False, default_factory=REAL)
    HHSeverity: DINT = field(init=False, default_factory=DINT)
    HLimit: REAL = field(init=False, default_factory=REAL)
    HSeverity: DINT = field(init=False, default_factory=DINT)
    LLimit: REAL = field(init=False, default_factory=REAL)
    LSeverity: DINT = field(init=False, default_factory=DINT)
    LLLimit: REAL = field(init=False, default_factory=REAL)
    LLSeverity: DINT = field(init=False, default_factory=DINT)
    MinDurationPRE: DINT = field(init=False, default_factory=DINT)
    ShelveDuration: DINT = field(init=False, default_factory=DINT)
    MaxShelveDuration: DINT = field(init=False, default_factory=DINT)
    Deadband: REAL = field(init=False, default_factory=REAL)
    ROCPosLimit: REAL = field(init=False, default_factory=REAL)
    ROCPosSeverity: DINT = field(init=False, default_factory=DINT)
    ROCNegLimit: REAL = field(init=False, default_factory=REAL)
    ROCNegSeverity: DINT = field(init=False, default_factory=DINT)
    ROCPeriod: REAL = field(init=False, default_factory=REAL)
    EnableOut: BOOL = field(init=False, default_factory=BOOL)
    InAlarm: BOOL = field(init=False, default_factory=BOOL)
    AnyInAlarmUnack: BOOL = field(init=False, default_factory=BOOL)
    HHInAlarm: BOOL = field(init=False, default_factory=BOOL)
    HInAlarm: BOOL = field(init=False, default_factory=BOOL)
    LInAlarm: BOOL = field(init=False, default_factory=BOOL)
    LLInAlarm: BOOL = field(init=False, default_factory=BOOL)
    ROCPosInAlarm: BOOL = field(init=False, default_factory=BOOL)
    ROCNegInAlarm: BOOL = field(init=False, default_factory=BOOL)
    ROC: BOOL = field(init=False, default_factory=BOOL)
    HHAcked: BOOL = field(init=False, default_factory=BOOL)
    HAcked: BOOL = field(init=False, default_factory=BOOL)
    LAcked: BOOL = field(init=False, default_factory=BOOL)
    LLAcked: BOOL = field(init=False, default_factory=BOOL)
    ROCPosAcked: BOOL = field(init=False, default_factory=BOOL)
    ROCNegAcked: BOOL = field(init=False, default_factory=BOOL)
    HHInAlarmUnack: BOOL = field(init=False, default_factory=BOOL)
    HInAlarmUnack: BOOL = field(init=False, default_factory=BOOL)
    LInAlarmUnack: BOOL = field(init=False, default_factory=BOOL)
    LLInAlarmUnack: BOOL = field(init=False, default_factory=BOOL)
    ROCPosInAlarmUnack: BOOL = field(init=False, default_factory=BOOL)
    ROCNegInAlarmUnack: BOOL = field(init=False, default_factory=BOOL)
    Suppressed: BOOL = field(init=False, default_factory=BOOL)
    HHShelved: BOOL = field(init=False, default_factory=BOOL)
    HShelved: BOOL = field(init=False, default_factory=BOOL)
    LShelved: BOOL = field(init=False, default_factory=BOOL)
    LLShelved: BOOL = field(init=False, default_factory=BOOL)
    ROCPosShelved: BOOL = field(init=False, default_factory=BOOL)
    ROCNegShelved: BOOL = field(init=False, default_factory=BOOL)
    Disabled: BOOL = field(init=False, default_factory=BOOL)
    Commissioned: BOOL = field(init=False, default_factory=BOOL)
    MinDurationACC: DINT = field(init=False, default_factory=DINT)
    HHInAlarmTime: LINT = field(init=False, default_factory=LINT)
    HHAlarmCount: DINT = field(init=False, default_factory=DINT)
    HInAlarmTime: LINT = field(init=False, default_factory=LINT)
    HAlarmCount: DINT = field(init=False, default_factory=DINT)
    LInAlarmTime: LINT = field(init=False, default_factory=LINT)
    LAlarmCount: DINT = field(init=False, default_factory=DINT)
    LLInAlarmTime: LINT = field(init=False, default_factory=LINT)
    LLAlarmCount: DINT = field(init=False, default_factory=DINT)
    ROCPosInAlarmTime: LINT = field(init=False, default_factory=LINT)
    ROCPosAlarmCount: DINT = field(init=False, default_factory=DINT)
    ROCNegInAlarmTime: LINT = field(init=False, default_factory=LINT)
    ROCNegAlarmCount: DINT = field(init=False, default_factory=DINT)
    AckTime: LINT = field(init=False, default_factory=LINT)
    RetToNormalTime: LINT = field(init=False, default_factory=LINT)
    AlarmCountResetTime: LINT = field(init=False, default_factory=LINT)
    ShelveTime: LINT = field(init=False, default_factory=LINT)
    UnshelveTime: LINT = field(init=False, default_factory=LINT)
    Status: DINT = field(init=False, default_factory=DINT)
    InstructFault: BOOL = field(init=False, default_factory=BOOL)
    InFaulted: BOOL = field(init=False, default_factory=BOOL)
    SeverityInv: BOOL = field(init=False, default_factory=BOOL)
    DeadbandInv: BOOL = field(init=False, default_factory=BOOL)
    ROCPosLimitInv: BOOL = field(init=False, default_factory=BOOL)
    ROCNegLimitInv: BOOL = field(init=False, default_factory=BOOL)
    ROCPeriodInv: BOOL = field(init=False, default_factory=BOOL)

@DataTypeRegistry.register
@dataclass
class ALARM_DIGITAL:
    EnableIn: BOOL = field(init=False, default_factory=BOOL)
    In: BOOL = field(init=False, default_factory=BOOL)
    InFault: BOOL = field(init=False, default_factory=BOOL)
    Condition: BOOL = field(init=False, default_factory=BOOL)
    AckRequired: BOOL = field(init=False, default_factory=BOOL)
    Latched: BOOL = field(init=False, default_factory=BOOL)
    ProgAck: BOOL = field(init=False, default_factory=BOOL)
    OperAck: BOOL = field(init=False, default_factory=BOOL)
    ProgReset: BOOL = field(init=False, default_factory=BOOL)
    OperReset: BOOL = field(init=False, default_factory=BOOL)
    ProgSuppress: BOOL = field(init=False, default_factory=BOOL)
    OperSuppress: BOOL = field(init=False, default_factory=BOOL)
    ProgUnsuppress: BOOL = field(init=False, default_factory=BOOL)
    OperUnsuppress: BOOL = field(init=False, default_factory=BOOL)
    OperShelve: BOOL = field(init=False, default_factory=BOOL)
    ProgUnshelve: BOOL = field(init=False, default_factory=BOOL)
    OperUnshelve: BOOL = field(init=False, default_factory=BOOL)
    ProgDisable: BOOL = field(init=False, default_factory=BOOL)
    OperDisable: BOOL = field(init=False, default_factory=BOOL)
    ProgEnable: BOOL = field(init=False, default_factory=BOOL)
    OperEnable: BOOL = field(init=False, default_factory=BOOL)
    AlarmCountReset: BOOL = field(init=False, default_factory=BOOL)
    UseProgTime: BOOL = field(init=False, default_factory=BOOL)
    ProgTime: LINT = field(init=False, default_factory=LINT)
    Severity: DINT = field(init=False, default_factory=DINT)
    MinDurationPRE: DINT = field(init=False, default_factory=DINT)
    ShelveDuration: DINT = field(init=False, default_factory=DINT)
    MaxShelveDuration: DINT = field(init=False, default_factory=DINT)
    EnableOut: BOOL = field(init=False, default_factory=BOOL)
    InAlarm: BOOL = field(init=False, default_factory=BOOL)
    Acked: BOOL = field(init=False, default_factory=BOOL)
    InAlarmUnack: BOOL = field(init=False, default_factory=BOOL)
    Suppressed: BOOL = field(init=False, default_factory=BOOL)
    Shelved: BOOL = field(init=False, default_factory=BOOL)
    Disabled: BOOL = field(init=False, default_factory=BOOL)
    Commissioned: BOOL = field(init=False, default_factory=BOOL)
    Shelved: DINT = field(init=False, default_factory=DINT)
    MinDurationACC: DINT = field(init=False, default_factory=DINT)
    AlarmCount: DINT = field(init=False, default_factory=DINT)
    Shelved: DINT = field(init=False, default_factory=DINT)
    InAlarmTime: LINT = field(init=False, default_factory=LINT)
    AckTime: LINT = field(init=False, default_factory=LINT)
    RetToNormalTime: LINT = field(init=False, default_factory=LINT)
    AlarmCountResetTime: LINT = field(init=False, default_factory=LINT)
    ShelveTime: LINT = field(init=False, default_factory=LINT)
    UnshelveTime: LINT = field(init=False, default_factory=LINT)
    InAlarmTime: LINT = field(init=False, default_factory=LINT)
    Status: DINT = field(init=False, default_factory=DINT)
    InstructFault: BOOL = field(init=False, default_factory=BOOL)
    InFaulted: BOOL = field(init=False, default_factory=BOOL)
    SeverityInv: BOOL = field(init=False, default_factory=BOOL)

@DataTypeRegistry.register
@dataclass
class ALARM_SET_CONTROL:
    EnableIn: BOOL = field(init=False, default_factory=BOOL)
    EnableOut: BOOL = field(init=False, default_factory=BOOL)
    LastState: BOOL = field(init=False, default_factory=BOOL)
