from dataclasses import dataclass, field

from asyncua import ua

from core.registry.datatyperegistry import DataTypeRegistry

from datatypes.custom.numbers import DINT, REAL
from datatypes.custom.bool import BOOL
from datatypes.custom.udt import UDT

@DataTypeRegistry.register
@dataclass
class DISCRETE_2STATE(UDT):
    EnableIn: BOOL = field(init=False, default_factory=BOOL)
    ProgCommand: BOOL = field(init=False, default_factory=BOOL)
    Oper0Req: BOOL = field(init=False, default_factory=BOOL)
    Oper1Req: BOOL = field(init=False, default_factory=BOOL)
    State0Perm: BOOL = field(init=False, default_factory=BOOL)
    State1Perm: BOOL = field(init=False, default_factory=BOOL)
    FB0: BOOL = field(init=False, default_factory=BOOL)
    FB1: BOOL = field(init=False, default_factory=BOOL)
    HandFB: BOOL = field(init=False, default_factory=BOOL)
    FaultTime: REAL = field(init=False, default_factory=REAL)
    FaultAlarmLatch: BOOL = field(init=False, default_factory=BOOL)
    FaultAlmUnlatch: BOOL = field(init=False, default_factory=BOOL)
    OverrideOnInit: BOOL = field(init=False, default_factory=BOOL)
    OverrideOnFault: BOOL = field(init=False, default_factory=BOOL)
    OutReverse: BOOL = field(init=False, default_factory=BOOL)
    OverrideState: BOOL = field(init=False, default_factory=BOOL)
    FB0State0: BOOL = field(init=False, default_factory=BOOL)
    FB0State1: BOOL = field(init=False, default_factory=BOOL)
    FB1State0: BOOL = field(init=False, default_factory=BOOL)
    FB1State1: BOOL = field(init=False, default_factory=BOOL)
    ProgProgReq: BOOL = field(init=False, default_factory=BOOL)
    ProgOperReq: BOOL = field(init=False, default_factory=BOOL)
    ProgOverrideReq: BOOL = field(init=False, default_factory=BOOL)
    ProgHandReq: BOOL = field(init=False, default_factory=BOOL)
    OperProgReq: BOOL = field(init=False, default_factory=BOOL)
    OperOperReq: BOOL = field(init=False, default_factory=BOOL)
    ProgValueReset: BOOL = field(init=False, default_factory=BOOL)
    EnableOut: BOOL = field(init=False, default_factory=BOOL)
    Out: BOOL = field(init=False, default_factory=BOOL)
    Device0State: BOOL = field(init=False, default_factory=BOOL)
    Device1State: BOOL = field(init=False, default_factory=BOOL)
    CommandStatus: BOOL = field(init=False, default_factory=BOOL)
    FaultAlarm: BOOL = field(init=False, default_factory=BOOL)
    ModeAlarm: BOOL = field(init=False, default_factory=BOOL)
    ProgOper: BOOL = field(init=False, default_factory=BOOL)
    Override: BOOL = field(init=False, default_factory=BOOL)
    Hand: BOOL = field(init=False, default_factory=BOOL)
    Status: DINT = field(init=False, default_factory=DINT)
    InstructFault: BOOL = field(init=False, default_factory=BOOL)
    FaultTimeInv: BOOL = field(init=False, default_factory=BOOL)
    OperReqInv: BOOL = field(init=False, default_factory=BOOL)

@DataTypeRegistry.register
@dataclass
class DISCRETE_3STATE(UDT):
    EnableIn: BOOL = field(init=False, default_factory=BOOL)
    Prog0Command: BOOL = field(init=False, default_factory=BOOL)
    Prog1Command: BOOL = field(init=False, default_factory=BOOL)
    Prog2Command: BOOL = field(init=False, default_factory=BOOL)
    Oper0Req: BOOL = field(init=False, default_factory=BOOL)
    Oper1Req: BOOL = field(init=False, default_factory=BOOL)
    Oper2Req: BOOL = field(init=False, default_factory=BOOL)
    State0Perm: BOOL = field(init=False, default_factory=BOOL)
    State1Perm: BOOL = field(init=False, default_factory=BOOL)
    State2Perm: BOOL = field(init=False, default_factory=BOOL)
    FB0: BOOL = field(init=False, default_factory=BOOL)
    FB1: BOOL = field(init=False, default_factory=BOOL)
    FB2: BOOL = field(init=False, default_factory=BOOL)
    FB3: BOOL = field(init=False, default_factory=BOOL)
    HandFB0: BOOL = field(init=False, default_factory=BOOL)
    HandFB1: BOOL = field(init=False, default_factory=BOOL)
    HandFB2: BOOL = field(init=False, default_factory=BOOL)
    FaultTime: REAL = field(init=False, default_factory=REAL)
    FaultAlarmLatch: BOOL = field(init=False, default_factory=BOOL)
    FaultAlmUnlatch: BOOL = field(init=False, default_factory=BOOL)
    OverrideOnInit: BOOL = field(init=False, default_factory=BOOL)
    OverrideOnFault: BOOL = field(init=False, default_factory=BOOL)
    Out0State0: BOOL = field(init=False, default_factory=BOOL)
    Out0State1: BOOL = field(init=False, default_factory=BOOL)
    Out0State2: BOOL = field(init=False, default_factory=BOOL)
    Out1State0: BOOL = field(init=False, default_factory=BOOL)
    Out1State1: BOOL = field(init=False, default_factory=BOOL)
    Out1State2: BOOL = field(init=False, default_factory=BOOL)
    Out2State0: BOOL = field(init=False, default_factory=BOOL)
    Out2State1: BOOL = field(init=False, default_factory=BOOL)
    Out2State2: BOOL = field(init=False, default_factory=BOOL)
    OverrideState: BOOL = field(init=False, default_factory=BOOL)
    FB0State0: BOOL = field(init=False, default_factory=BOOL)
    FB0State1: BOOL = field(init=False, default_factory=BOOL)
    FB0State2: BOOL = field(init=False, default_factory=BOOL)
    FB1State0: BOOL = field(init=False, default_factory=BOOL)
    FB1State1: BOOL = field(init=False, default_factory=BOOL)
    FB1State2: BOOL = field(init=False, default_factory=BOOL)
    FB2State0: BOOL = field(init=False, default_factory=BOOL)
    FB2State1: BOOL = field(init=False, default_factory=BOOL)
    FB2State2: BOOL = field(init=False, default_factory=BOOL)
    FB3State0: BOOL = field(init=False, default_factory=BOOL)
    FB3State1: BOOL = field(init=False, default_factory=BOOL)
    FB3State2: BOOL = field(init=False, default_factory=BOOL)
    ProgProgReq: BOOL = field(init=False, default_factory=BOOL)
    ProgOperReq: BOOL = field(init=False, default_factory=BOOL)
    ProgOverrideReq: BOOL = field(init=False, default_factory=BOOL)
    ProgHandReq: BOOL = field(init=False, default_factory=BOOL)
    OperProgReq: BOOL = field(init=False, default_factory=BOOL)
    OperOperReq: BOOL = field(init=False, default_factory=BOOL)
    ProgValueReset: BOOL = field(init=False, default_factory=BOOL)
    EnableOut: BOOL = field(init=False, default_factory=BOOL)
    Out0: BOOL = field(init=False, default_factory=BOOL)
    Out1: BOOL = field(init=False, default_factory=BOOL)
    Out2: BOOL = field(init=False, default_factory=BOOL)    
    Device0State: BOOL = field(init=False, default_factory=BOOL)
    Device1State: BOOL = field(init=False, default_factory=BOOL)
    Device2State: BOOL = field(init=False, default_factory=BOOL)
    Command0Status: BOOL = field(init=False, default_factory=BOOL)
    Command1Status: BOOL = field(init=False, default_factory=BOOL)
    Command2Status: BOOL = field(init=False, default_factory=BOOL)
    FaultAlarm: BOOL = field(init=False, default_factory=BOOL)
    ModeAlarm: BOOL = field(init=False, default_factory=BOOL)
    ProgOper: BOOL = field(init=False, default_factory=BOOL)
    Override: BOOL = field(init=False, default_factory=BOOL)
    Hand: BOOL = field(init=False, default_factory=BOOL)
    Status: DINT = field(init=False, default_factory=DINT)
    InstructFault: BOOL = field(init=False, default_factory=BOOL)
    FaultTimeInv: BOOL = field(init=False, default_factory=BOOL)
    OverrideStateInv: BOOL = field(init=False, default_factory=BOOL)
    ProgCommandInv: BOOL = field(init=False, default_factory=BOOL)
    OperReqInv: BOOL = field(init=False, default_factory=BOOL)
    HandCommandInv: BOOL = field(init=False, default_factory=BOOL)