from dataclasses import dataclass, field

from core.registry.datatyperegistry import DataTypeRegistry

from datatypes.custom.numbers import DINT, REAL
from datatypes.custom.bool import BOOL, MEMORY_BIT
from datatypes.custom.udt import _R32BIT_UDT

from core.l5k.l5kreader import L5KBOOLBYTEEND, L5KSKIP

@DataTypeRegistry.register
@dataclass
class DISCRETE_2STATE(_R32BIT_UDT):

    def __post_init__(self):
        self.InstructFault = MEMORY_BIT(self.Status, 0)
        self.FaultTimeInv = MEMORY_BIT(self.Status, 1)
        self.OperReqInv = MEMORY_BIT(self.Status, 2)

    EnableIn: BOOL = field(init=False, default_factory=BOOL)
    ProgCommand: BOOL = field(init=False, default_factory=BOOL)
    Oper0Req: BOOL = field(init=False, default_factory=BOOL)
    Oper1Req: BOOL = field(init=False, default_factory=BOOL)
    State0Perm: BOOL = field(init=False, default_factory=BOOL)
    State1Perm: BOOL = field(init=False, default_factory=BOOL)
    FB0: BOOL = field(init=False, default_factory=BOOL)
    FB1: BOOL = field(init=False, default_factory=BOOL)
    HandFB: BOOL = field(init=False, default_factory=BOOL)
    FaultTime: REAL = field(init=False, default_factory=REAL)
    FaultAlarmLatch: BOOL = field(init=False, default_factory=BOOL)
    FaultAlmUnlatch: BOOL = field(init=False, default_factory=BOOL)
    OverrideOnInit: BOOL = field(init=False, default_factory=BOOL)
    OverrideOnFault: BOOL = field(init=False, default_factory=BOOL)
    OutReverse: BOOL = field(init=False, default_factory=BOOL)
    OverrideState: BOOL = field(init=False, default_factory=BOOL)
    FB0State0: BOOL = field(init=False, default_factory=BOOL)
    FB0State1: BOOL = field(init=False, default_factory=BOOL)
    FB1State0: BOOL = field(init=False, default_factory=BOOL)
    FB1State1: BOOL = field(init=False, default_factory=BOOL)
    ProgProgReq: BOOL = field(init=False, default_factory=BOOL)
    ProgOperReq: BOOL = field(init=False, default_factory=BOOL)
    ProgOverrideReq: BOOL = field(init=False, default_factory=BOOL)
    ProgHandReq: BOOL = field(init=False, default_factory=BOOL)
    OperProgReq: BOOL = field(init=False, default_factory=BOOL)
    OperOperReq: BOOL = field(init=False, default_factory=BOOL)
    ProgValueReset: BOOL = field(init=False, default_factory=BOOL, metadata=L5KBOOLBYTEEND)
    EnableOut: BOOL = field(init=False, default_factory=BOOL)
    Out: BOOL = field(init=False, default_factory=BOOL)
    Device0State: BOOL = field(init=False, default_factory=BOOL)
    Device1State: BOOL = field(init=False, default_factory=BOOL)
    CommandStatus: BOOL = field(init=False, default_factory=BOOL)
    FaultAlarm: BOOL = field(init=False, default_factory=BOOL)
    ModeAlarm: BOOL = field(init=False, default_factory=BOOL)
    ProgOper: BOOL = field(init=False, default_factory=BOOL)
    Override: BOOL = field(init=False, default_factory=BOOL)
    Hand: BOOL = field(init=False, default_factory=BOOL)
    Status: DINT = field(init=False, default_factory=DINT)
    InstructFault: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    FaultTimeInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    OperReqInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)

@DataTypeRegistry.register
@dataclass
class DISCRETE_3STATE(_R32BIT_UDT):

    def __post_init__(self):
        self.InstructFault = MEMORY_BIT(self.Status, 0)
        self.FaultTimeInv = MEMORY_BIT(self.Status, 1)
        self.OverrideStateInv = MEMORY_BIT(self.Status, 2)
        self.ProgCommandInv = MEMORY_BIT(self.Status, 3)
        self.OperReqInv = MEMORY_BIT(self.Status, 4)
        self.HandCommandInv = MEMORY_BIT(self.Status, 5)

    EnableIn: BOOL = field(init=False, default_factory=BOOL)
    Prog0Command: BOOL = field(init=False, default_factory=BOOL)
    Prog1Command: BOOL = field(init=False, default_factory=BOOL)
    Prog2Command: BOOL = field(init=False, default_factory=BOOL)
    Oper0Req: BOOL = field(init=False, default_factory=BOOL)
    Oper1Req: BOOL = field(init=False, default_factory=BOOL)
    Oper2Req: BOOL = field(init=False, default_factory=BOOL)
    State0Perm: BOOL = field(init=False, default_factory=BOOL)
    State1Perm: BOOL = field(init=False, default_factory=BOOL)
    State2Perm: BOOL = field(init=False, default_factory=BOOL)
    FB0: BOOL = field(init=False, default_factory=BOOL)
    FB1: BOOL = field(init=False, default_factory=BOOL)
    FB2: BOOL = field(init=False, default_factory=BOOL)
    FB3: BOOL = field(init=False, default_factory=BOOL)
    HandFB0: BOOL = field(init=False, default_factory=BOOL)
    HandFB1: BOOL = field(init=False, default_factory=BOOL)
    HandFB2: BOOL = field(init=False, default_factory=BOOL)
    FaultAlarmLatch: BOOL = field(init=False, default_factory=BOOL)
    FaultAlmUnlatch: BOOL = field(init=False, default_factory=BOOL)
    OverrideOnInit: BOOL = field(init=False, default_factory=BOOL)
    OverrideOnFault: BOOL = field(init=False, default_factory=BOOL)
    Out0State0: BOOL = field(init=False, default_factory=BOOL)
    Out0State1: BOOL = field(init=False, default_factory=BOOL)
    Out0State2: BOOL = field(init=False, default_factory=BOOL)
    Out1State0: BOOL = field(init=False, default_factory=BOOL)
    Out1State1: BOOL = field(init=False, default_factory=BOOL)
    Out1State2: BOOL = field(init=False, default_factory=BOOL)
    Out2State0: BOOL = field(init=False, default_factory=BOOL)
    Out2State1: BOOL = field(init=False, default_factory=BOOL)
    Out2State2: BOOL = field(init=False, default_factory=BOOL)
    FB0State0: BOOL = field(init=False, default_factory=BOOL)
    FB0State1: BOOL = field(init=False, default_factory=BOOL)
    FB0State2: BOOL = field(init=False, default_factory=BOOL)
    FB1State0: BOOL = field(init=False, default_factory=BOOL)
    FB1State1: BOOL = field(init=False, default_factory=BOOL)
    FB1State2: BOOL = field(init=False, default_factory=BOOL)
    FB2State0: BOOL = field(init=False, default_factory=BOOL)
    FB2State1: BOOL = field(init=False, default_factory=BOOL)
    FB2State2: BOOL = field(init=False, default_factory=BOOL)
    FB3State0: BOOL = field(init=False, default_factory=BOOL)
    FB3State1: BOOL = field(init=False, default_factory=BOOL)
    FB3State2: BOOL = field(init=False, default_factory=BOOL)
    ProgProgReq: BOOL = field(init=False, default_factory=BOOL)
    ProgOperReq: BOOL = field(init=False, default_factory=BOOL)
    ProgOverrideReq: BOOL = field(init=False, default_factory=BOOL)
    ProgHandReq: BOOL = field(init=False, default_factory=BOOL)
    OperProgReq: BOOL = field(init=False, default_factory=BOOL)
    OperOperReq: BOOL = field(init=False, default_factory=BOOL)
    ProgValueReset: BOOL = field(init=False, default_factory=BOOL)
    FaultTime: REAL = field(init=False, default_factory=REAL)    
    OverrideState: DINT = field(init=False, default_factory=DINT)
    EnableOut: BOOL = field(init=False, default_factory=BOOL)
    Out0: BOOL = field(init=False, default_factory=BOOL)
    Out1: BOOL = field(init=False, default_factory=BOOL)
    Out2: BOOL = field(init=False, default_factory=BOOL)    
    Device0State: BOOL = field(init=False, default_factory=BOOL)
    Device1State: BOOL = field(init=False, default_factory=BOOL)
    Device2State: BOOL = field(init=False, default_factory=BOOL)
    Command0Status: BOOL = field(init=False, default_factory=BOOL)
    Command1Status: BOOL = field(init=False, default_factory=BOOL)
    Command2Status: BOOL = field(init=False, default_factory=BOOL)
    FaultAlarm: BOOL = field(init=False, default_factory=BOOL)
    ModeAlarm: BOOL = field(init=False, default_factory=BOOL)
    ProgOper: BOOL = field(init=False, default_factory=BOOL)
    Override: BOOL = field(init=False, default_factory=BOOL)
    Hand: BOOL = field(init=False, default_factory=BOOL)
    Status: DINT = field(init=False, default_factory=DINT)
    InstructFault: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    FaultTimeInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    OverrideStateInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    ProgCommandInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    OperReqInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    HandCommandInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)