from dataclasses import dataclass, field

from core.registry.datatyperegistry import DataTypeRegistry

from datatypes.custom.numbers import DINT, REAL
from datatypes.custom.bool import BOOL, MEMORY_BIT
from datatypes.custom.array import Array
from datatypes.custom.udt import UDT, _32BIT_UDT

from core.l5k.l5kreader import L5KSKIP, L5KBOOLBYTEEND

@DataTypeRegistry.register
@dataclass
class PID(UDT):

    def __post_init__(self):
        self.EN = MEMORY_BIT(self.CTL, 31)
        self.CT = MEMORY_BIT(self.CTL, 30)
        self.CL = MEMORY_BIT(self.CTL, 29)
        self.PVT = MEMORY_BIT(self.CTL, 28)
        self.DOE = MEMORY_BIT(self.CTL, 27)
        self.SWM = MEMORY_BIT(self.CTL, 26)
        self.CA = MEMORY_BIT(self.CTL, 25)
        self.MO = MEMORY_BIT(self.CTL, 24)
        self.PE = MEMORY_BIT(self.CTL, 23)
        self.NDF = MEMORY_BIT(self.CTL, 22)
        self.NOBC = MEMORY_BIT(self.CTL, 21)
        self.NOZC = MEMORY_BIT(self.CTL, 20)
        self.INI = MEMORY_BIT(self.CTL, 19)
        self.SPOR = MEMORY_BIT(self.CTL, 18)
        self.OLL = MEMORY_BIT(self.CTL, 17)
        self.OLH = MEMORY_BIT(self.CTL, 16)
        self.EWD = MEMORY_BIT(self.CTL, 15)
        self.DVNA = MEMORY_BIT(self.CTL, 14)
        self.DVPA = MEMORY_BIT(self.CTL, 13)
        self.PVLA = MEMORY_BIT(self.CTL, 12)
        self.PVHA = MEMORY_BIT(self.CTL, 10)

    CTL: DINT = field(init=False, default_factory=DINT)
    EN: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    CT: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    CL: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    PVT: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    DOE: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    SWM: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    CA: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    MO: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    PE: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    NDF: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    NOBC: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    NOZC: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    INI: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    SPOR: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    OLL: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    OLH: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    EWD: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    DVNA: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    DVPA: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    PVLA: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    PVHA: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    SP: REAL = field(init=False, default_factory=REAL)
    KP: REAL = field(init=False, default_factory=REAL)
    KI: REAL = field(init=False, default_factory=REAL)
    KD: REAL = field(init=False, default_factory=REAL)
    BIAS: REAL = field(init=False, default_factory=REAL)
    MAXS: REAL = field(init=False, default_factory=REAL)
    MINS: REAL = field(init=False, default_factory=REAL)
    DB: REAL = field(init=False, default_factory=REAL)
    SO: REAL = field(init=False, default_factory=REAL)
    MAXO: REAL = field(init=False, default_factory=REAL)
    MINO: REAL = field(init=False, default_factory=REAL)
    UPD: REAL = field(init=False, default_factory=REAL)
    PV: REAL = field(init=False, default_factory=REAL)
    ERR: REAL = field(init=False, default_factory=REAL)
    OUT: REAL = field(init=False, default_factory=REAL)
    PVH: REAL = field(init=False, default_factory=REAL)
    PVL: REAL = field(init=False, default_factory=REAL)
    DVP: REAL = field(init=False, default_factory=REAL)
    DVN: REAL = field(init=False, default_factory=REAL)
    PVDB: REAL = field(init=False, default_factory=REAL)
    DVDB: REAL = field(init=False, default_factory=REAL)
    MAXI: REAL = field(init=False, default_factory=REAL)
    MINI: REAL = field(init=False, default_factory=REAL)
    TIE: REAL = field(init=False, default_factory=REAL)
    MAXCV: REAL = field(init=False, default_factory=REAL)
    MINCV: REAL = field(init=False, default_factory=REAL)
    MINTIE: REAL = field(init=False, default_factory=REAL)
    MAXTIE: REAL = field(init=False, default_factory=REAL)
    DATA: Array[REAL] = field(init=False, default_factory=lambda: Array.create(REAL, 17))

@DataTypeRegistry.register
@dataclass
class PID_AUTOTUNE(UDT):
    ProcessType: DINT = field(init=False, default_factory=DINT)
    ResponseSpeed: DINT = field(init=False, default_factory=DINT)
    TestLength: REAL = field(init=False, default_factory=REAL)
    PVTuneLimit: REAL = field(init=False, default_factory=REAL)
    StepSize: REAL = field(init=False, default_factory=REAL)
    TunedGood: BOOL = field(init=False, default_factory=BOOL)
    TunedUncertain: BOOL = field(init=False, default_factory=BOOL)
    ATuneAcquired: BOOL = field(init=False, default_factory=BOOL)
    UsedProcessType: DINT = field(init=False, default_factory=DINT)
    Gain: REAL = field(init=False, default_factory=REAL)
    TimeConstant: REAL = field(init=False, default_factory=REAL)
    DeadTime: REAL = field(init=False, default_factory=REAL)
    PGainTunedFast: REAL = field(init=False, default_factory=REAL)
    IGainTunedFast: REAL = field(init=False, default_factory=REAL)
    DGainTunedFast: REAL = field(init=False, default_factory=REAL)
    PGainTunedMed: REAL = field(init=False, default_factory=REAL)
    IGainTunedMed: REAL = field(init=False, default_factory=REAL)
    DGainTunedMed: REAL = field(init=False, default_factory=REAL)
    PGainTunedSlow: REAL = field(init=False, default_factory=REAL)
    IGainTunedSlow: REAL = field(init=False, default_factory=REAL)
    DGainTunedSlow: REAL = field(init=False, default_factory=REAL)
    StepSizeUsed: REAL = field(init=False, default_factory=REAL)
    AtuneStatus: DINT = field(init=False, default_factory=DINT)
    ATuneFault: BOOL = field(init=False, default_factory=BOOL)
    PVOutOfLimit: BOOL = field(init=False, default_factory=BOOL)
    ModeInv: BOOL = field(init=False, default_factory=BOOL)
    CVWindupFault: BOOL = field(init=False, default_factory=BOOL)
    StepSizeZero: BOOL = field(init=False, default_factory=BOOL)
    CVLimitsFault: BOOL = field(init=False, default_factory=BOOL)
    CVInitFault: BOOL = field(init=False, default_factory=BOOL)
    EUSpanChanged: BOOL = field(init=False, default_factory=BOOL)
    CVChanged: BOOL = field(init=False, default_factory=BOOL)
    ATuneTimedOut: BOOL = field(init=False, default_factory=BOOL)
    PVNotSettled: BOOL = field(init=False, default_factory=BOOL)
    PVChangeTooSmall: BOOL = field(init=False, default_factory=BOOL)
    StepSizeTooSmall: BOOL = field(init=False, default_factory=BOOL)
    GainTooLarge: BOOL = field(init=False, default_factory=BOOL)
    GainTooSmall: BOOL = field(init=False, default_factory=BOOL)
    LongDeadTime: BOOL = field(init=False, default_factory=BOOL)

@DataTypeRegistry.register
@dataclass
class PID_ENHANCED(_32BIT_UDT):

    def __post_init__(self):
        self.InstructFault = MEMORY_BIT(self.Status1, 0)
        self.PVFaulted = MEMORY_BIT(self.Status1, 1)
        self.CVFaulted = MEMORY_BIT(self.Status1, 2)
        self.HandFBFaulted = MEMORY_BIT(self.Status1, 3)
        self.PVSpanInv = MEMORY_BIT(self.Status1, 4)
        self.SPOperInv = MEMORY_BIT(self.Status1, 5)
        self.SPCascadeInv = MEMORY_BIT(self.Status1, 6)
        self.SPLimitsInv = MEMORY_BIT(self.Status1, 7)
        self.RatioProgInv = MEMORY_BIT(self.Status1, 8)
        self.RatioOperInv = MEMORY_BIT(self.Status1, 9)
        self.RatioLimitsInv = MEMORY_BIT(self.Status1, 10)
        self.CVProgInv = MEMORY_BIT(self.Status1, 11)
        self.CVOperInv = MEMORY_BIT(self.Status1, 12)
        self.CVOverrideInv = MEMORY_BIT(self.Status1, 13)
        self.CVPreviousInv = MEMORY_BIT(self.Status1, 14)
        self.CVEUSpanInv = MEMORY_BIT(self.Status1, 15)
        self.CVLimitsInv = MEMORY_BIT(self.Status1, 16)
        self.CVROCLimitInv = MEMORY_BIT(self.Status1, 17)
        self.FFInv = MEMORY_BIT(self.Status1, 18)
        self.FFPreviousInv = MEMORY_BIT(self.Status1, 19)
        self.HandFBInv = MEMORY_BIT(self.Status1, 20)
        self.PGainInv = MEMORY_BIT(self.Status1, 21)
        self.IGainInv = MEMORY_BIT(self.Status1, 22)
        self.DGainInv = MEMORY_BIT(self.Status1, 23)
        self.ZCDeadbandInv = MEMORY_BIT(self.Status1, 24)
        self.PVDeadbandInv = MEMORY_BIT(self.Status1, 25)
        self.PVROCLimitsInv = MEMORY_BIT(self.Status1, 26)
        self.DevHLLimitsInv = MEMORY_BIT(self.Status1, 27)
        self.DevDeadbandInv = MEMORY_BIT(self.Status1, 28)

        self.AtuneDataInv = MEMORY_BIT(self.Status2, 1)
        self.TimingModeInv = MEMORY_BIT(self.Status2, 27)
        self.RTSMissed = MEMORY_BIT(self.Status2, 28)
        self.RTSTimeInv = MEMORY_BIT(self.Status2, 29)
        self.RTSTimeStampInv = MEMORY_BIT(self.Status2, 30)
        self.DeltaTInv = MEMORY_BIT(self.Status2, 31)

    EnableIn: BOOL = field(init=False, default_factory=BOOL, metadata=L5KBOOLBYTEEND)

    PVFault: BOOL = field(init=False, default_factory=BOOL)
    UseRatio: BOOL = field(init=False, default_factory=BOOL)
    CVFault: BOOL = field(init=False, default_factory=BOOL)
    CVInitReq: BOOL = field(init=False, default_factory=BOOL)
    CVSetPrevious: BOOL = field(init=False, default_factory=BOOL)
    CVManLimiting: BOOL = field(init=False, default_factory=BOOL)
    FFSetPrevious: BOOL = field(init=False, default_factory=BOOL)
    HandFBFault: BOOL = field(init=False, default_factory=BOOL)
    WindupHIn: BOOL = field(init=False, default_factory=BOOL)
    WindupLIn: BOOL = field(init=False, default_factory=BOOL)
    ControlAction: BOOL = field(init=False, default_factory=BOOL)
    DependIndepend: BOOL = field(init=False, default_factory=BOOL)
    PVEProportional: BOOL = field(init=False, default_factory=BOOL)
    PVEDerivative: BOOL = field(init=False, default_factory=BOOL)
    DSmoothing: BOOL = field(init=False, default_factory=BOOL)
    PVTracking: BOOL = field(init=False, default_factory=BOOL)
    ZCOff: BOOL = field(init=False, default_factory=BOOL)
    AllowCasRat: BOOL = field(init=False, default_factory=BOOL)
    ManualAfterInit: BOOL = field(init=False, default_factory=BOOL)
    ProgProgReq: BOOL = field(init=False, default_factory=BOOL)
    ProgOperReq: BOOL = field(init=False, default_factory=BOOL)
    ProgCasRatReq: BOOL = field(init=False, default_factory=BOOL)
    ProgAutoReq: BOOL = field(init=False, default_factory=BOOL)
    ProgManualReq: BOOL = field(init=False, default_factory=BOOL)
    ProgOverrideReq: BOOL = field(init=False, default_factory=BOOL)
    ProgHandReq: BOOL = field(init=False, default_factory=BOOL)
    OperProgReq: BOOL = field(init=False, default_factory=BOOL)
    OperOperReq: BOOL = field(init=False, default_factory=BOOL)
    OperCasRatReq: BOOL = field(init=False, default_factory=BOOL)
    OperAutoReq: BOOL = field(init=False, default_factory=BOOL)
    OperManualReq: BOOL = field(init=False, default_factory=BOOL)
    ProgValueReset: BOOL = field(init=False, default_factory=BOOL, metadata=L5KBOOLBYTEEND)
    
    PV: REAL = field(init=False, default_factory=REAL)
    PVEUMax: REAL = field(init=False, default_factory=REAL)
    PVEUMin: REAL = field(init=False, default_factory=REAL)
    SPProg: REAL = field(init=False, default_factory=REAL)
    SPOper: REAL = field(init=False, default_factory=REAL)
    SPCascade: REAL = field(init=False, default_factory=REAL)
    SPHLimit: REAL = field(init=False, default_factory=REAL)
    SPLLimit: REAL = field(init=False, default_factory=REAL)
    RatioProg: REAL = field(init=False, default_factory=REAL)
    RatioOper: REAL = field(init=False, default_factory=REAL)
    RatioHLimit: REAL = field(init=False, default_factory=REAL)
    RatioLLimit: REAL = field(init=False, default_factory=REAL)
    CVInitValue: REAL = field(init=False, default_factory=REAL)
    CVProg: REAL = field(init=False, default_factory=REAL)
    CVOper: REAL = field(init=False, default_factory=REAL)
    CVOverride: REAL = field(init=False, default_factory=REAL)
    CVPrevious: REAL = field(init=False, default_factory=REAL)
    CVEUMax: REAL = field(init=False, default_factory=REAL)
    CVEUMin: REAL = field(init=False, default_factory=REAL)
    CVHLimit: REAL = field(init=False, default_factory=REAL)
    CVLLimit: REAL = field(init=False, default_factory=REAL)
    CVROCLimit: REAL = field(init=False, default_factory=REAL)
    FF: REAL = field(init=False, default_factory=REAL)
    FFPrevious: REAL = field(init=False, default_factory=REAL)
    HandFB: REAL = field(init=False, default_factory=REAL)
    PGain: REAL = field(init=False, default_factory=REAL)
    IGain: REAL = field(init=False, default_factory=REAL)
    DGain: REAL = field(init=False, default_factory=REAL)
    ZCDeadband: REAL = field(init=False, default_factory=REAL)
    PVHHLimit: REAL = field(init=False, default_factory=REAL)
    PVHLimit: REAL = field(init=False, default_factory=REAL)
    PVLLimit: REAL = field(init=False, default_factory=REAL)
    PVLLLimit: REAL = field(init=False, default_factory=REAL)
    PVDeadband: REAL = field(init=False, default_factory=REAL)
    PVROCPosLimit: REAL = field(init=False, default_factory=REAL)
    PVROCNegLimit: REAL = field(init=False, default_factory=REAL)
    PVROCPeriod: REAL = field(init=False, default_factory=REAL)
    DevHHLimit: REAL = field(init=False, default_factory=REAL)
    DevHLimit: REAL = field(init=False, default_factory=REAL)
    DevLLimit: REAL = field(init=False, default_factory=REAL)
    DevLLLimit: REAL = field(init=False, default_factory=REAL)
    DevDeadband: REAL = field(init=False, default_factory=REAL)
    TimingMode: DINT = field(init=False, default_factory=DINT)
    OversampleDT: REAL = field(init=False, default_factory=REAL)
    RTSTime: DINT = field(init=False, default_factory=DINT)
    RTSTimeStamp: DINT = field(init=False, default_factory=DINT)
    AtuneAcquire: BOOL = field(init=False, default_factory=BOOL)
    AtuneStart: BOOL = field(init=False, default_factory=BOOL)
    AtuneUseGains: BOOL = field(init=False, default_factory=BOOL)
    AtuneAbort: BOOL = field(init=False, default_factory=BOOL)
    AtuneUnacquire: BOOL = field(init=False, default_factory=BOOL, metadata=L5KBOOLBYTEEND)

    EnableOut: BOOL = field(init=False, default_factory=BOOL, metadata=L5KBOOLBYTEEND)

    CVInitializing: BOOL = field(init=False, default_factory=BOOL)
    CVHAlarm: BOOL = field(init=False, default_factory=BOOL)
    CVLAlarm: BOOL = field(init=False, default_factory=BOOL)
    CVROCAlarm: BOOL = field(init=False, default_factory=BOOL)
    SPHAlarm: BOOL = field(init=False, default_factory=BOOL)
    SPLAlarm: BOOL = field(init=False, default_factory=BOOL)
    InitPrimary: BOOL = field(init=False, default_factory=BOOL)
    WindupHOut: BOOL = field(init=False, default_factory=BOOL)
    WindupLOut: BOOL = field(init=False, default_factory=BOOL)
    RatioHAlarm: BOOL = field(init=False, default_factory=BOOL)
    RatioLAlarm: BOOL = field(init=False, default_factory=BOOL)
    ZCDeadbandOn: BOOL = field(init=False, default_factory=BOOL)
    PVHHAlarm: BOOL = field(init=False, default_factory=BOOL)
    PVHAlarm: BOOL = field(init=False, default_factory=BOOL)
    PVLAlarm: BOOL = field(init=False, default_factory=BOOL)
    PVLLAlarm: BOOL = field(init=False, default_factory=BOOL)
    PVROCPosAlarm: BOOL = field(init=False, default_factory=BOOL)
    PVROCNegAlarm: BOOL = field(init=False, default_factory=BOOL)
    DevHHAlarm: BOOL = field(init=False, default_factory=BOOL)
    DevHAlarm: BOOL = field(init=False, default_factory=BOOL)
    DevLAlarm: BOOL = field(init=False, default_factory=BOOL)
    DevLLAlarm: BOOL = field(init=False, default_factory=BOOL)
    ProgOper: BOOL = field(init=False, default_factory=BOOL)
    CasRat: BOOL = field(init=False, default_factory=BOOL)
    Auto: BOOL = field(init=False, default_factory=BOOL)
    Manual: BOOL = field(init=False, default_factory=BOOL)
    Override: BOOL = field(init=False, default_factory=BOOL)
    Hand: BOOL = field(init=False, default_factory=BOOL, metadata=L5KBOOLBYTEEND)

    CVEU: REAL = field(init=False, default_factory=REAL)
    CV: REAL = field(init=False, default_factory=REAL)
    SP: REAL = field(init=False, default_factory=REAL)
    SPPercent: REAL = field(init=False, default_factory=REAL)
    PVPercent: REAL = field(init=False, default_factory=REAL)
    E: REAL = field(init=False, default_factory=REAL)
    EPercent: REAL = field(init=False, default_factory=REAL)
    Ratio: REAL = field(init=False, default_factory=REAL)
    DeltaT: REAL = field(init=False, default_factory=REAL)
    AtuneReady: BOOL = field(init=False, default_factory=BOOL)
    AtuneOn: BOOL = field(init=False, default_factory=BOOL)
    AtuneDone: BOOL = field(init=False, default_factory=BOOL)
    AtuneAborted: BOOL = field(init=False, default_factory=BOOL)
    AtuneBusy: BOOL = field(init=False, default_factory=BOOL)
    Status1: DINT = field(init=False, default_factory=DINT)
    Status2: DINT = field(init=False, default_factory=DINT)
    InstructFault: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    PVFaulted: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    CVFaulted: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    HandFBFaulted: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    PVSpanInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    SPProgInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    SPOperInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    SPCascadeInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    SPLimitsInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    RatioProgInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    RatioOperInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    RatioLimitsInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    CVProgInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    CVOperInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    CVOverrideInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    CVPreviousInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    CVEUSpanInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    CVLimitsInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    CVROCLimitInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    FFInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    FFPreviousInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    HandFBInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    PGainInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    IGainInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    DGainInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    ZCDeadbandInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    PVDeadbandInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    PVROCLimitsInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    DevHLLimitsInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    DevDeadbandInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    AtuneDataInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    TimingModeInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    RTSMissed: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    RTSTimeInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    RTSTimeStampInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)
    DeltaTInv: BOOL = field(init=False, default_factory=BOOL, metadata=L5KSKIP)